framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # task-tracker-events - события для других сервисов. Только на публикацию
            task-tracker-events:
                dsn: '%env(MESSENGER_TRANSPORT_DSN_TASK_TRACKER_EVENTS)%'
                serializer: Razikov\AtesTaskTracker\Service\ExternalJsonMessageSerializer
                retry_strategy:
                    max_retries: 0
            # auth-events события из auth сервиса. Только на чтение
            auth-events:
                dsn: '%env(MESSENGER_TRANSPORT_DSN_AUTH_EVENTS)%'
                serializer: Razikov\AtesTaskTracker\Service\ExternalJsonMessageSerializer
                retry_strategy:
                    max_retries: 0
                options:
                    queues:
                        authEventsTaskTracker: ~

        routing:
            # Route your messages to the transports
            'Razikov\AtesTaskTracker\Feature\CreateUser\Command': sync
            'Razikov\AtesTaskTracker\Feature\CreateTask\Command': sync
            'Razikov\AtesTaskTracker\Feature\CreateTask\TaskCreatedEvent': task-tracker-events
            'Razikov\AtesTaskTracker\Feature\AssignTasks\Command': sync
            'Razikov\AtesTaskTracker\Feature\AssignTasks\TaskAssignedEvent': task-tracker-events
            'Razikov\AtesTaskTracker\Feature\CompleteTask\Command': sync
            'Razikov\AtesTaskTracker\Feature\CompleteTask\TaskCompletedEvent': task-tracker-events
            'Razikov\AtesTaskTracker\Feature\GetDashboardView\Command': sync
            'Razikov\AtesTaskTracker\Feature\GetPersonalDashboardView\Command': sync

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
