POST http://rest.ates-task:8001/api/v1/task
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjUyNTQ2MzgsImV4cCI6MTY2NTI1ODIzOCwicm9sZXMiOlsiUk9MRV9BRE1JTiJdLCJ1c2VybmFtZSI6ImFkbWluQGxvY2FsaG9zdC5kZXYiLCJ1c2VySWQiOiIwMTgzYjhkMC0xOTJkLTdhYTQtODA0Ni1lZGNmOGQ0MGU4OGMifQ.jxu-pQ3vVpfJVf2GaRqFyuApyxe1LDQTyI4QDLAfw3O6xz0kZ6DWNt9TGEx7XvPmyh9qelu7dChkbIU17-bLO9TISe6f4VMHqXVdaXftym4HNtT_UkpbzEK18BeCwUwoDQbiq7M3oCSSocLx_T3I0flCJAJE_JB8HiWuQIm-UZYqF3p6BKdzLuCu7bmCvEc6Wl1vhxQFVyS5wStQmZ16s9Gk0JplR9S6zDOdVN4-SpENQz1cRJXClnSyW94DTpl1eJt69jYtl9fwnUK8I4blvOM-Af6aaqvba5pZSqL-y6pPdQ2ga2zIc3DUIaOjDR0VlmwMY-BCjazg2uq7j6SEaA

{
  "description": "test task15 description"
}

###

PUT http://rest.ates-task:8001/api/v1/task/shuffle
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjUwMTI5ODksImV4cCI6MTY2NTAxNjU4OSwicm9sZXMiOlsiUk9MRV9BRE1JTiJdLCJ1c2VybmFtZSI6ImFkbWluQGxvY2FsaG9zdC5kZXYiLCJ1c2VySWQiOiIwMTgzOWZkYS00MjEyLTc0OTUtODIyNS02OTE5M2E2YWM0MTUifQ.lzk9l8tX3N-aKOMYYFPjQPy6ORTdb7e6o_kyt_JTx4oqJIymsruRFPQZSabGO3JdA2zNWmaW4IF5XXu6R2l5WUO6UPFWIhDUvPGaakBl3Vo_4WgwW0gINxTOxnk0kdL3V278iUq-PuLpj_CkcYVsNDIHHJIrfZZWINSWL5Ny_9ELOHZz22eAXrtAPoLJLwuAIB-EpiclGgfjkJu_sgIuQBrTK0gnafKeUTKA1YKd-bgUubwFalA2eQeI-Kp1FcK6lDPuVjr-O6xWHey5e5n6AQF48RudRT8j6mukIZBSEYg2VgGct_KiEbWmDe_TyfcATgXdjUSy98dflrEEkudlrQ

###

PUT http://rest.ates-task:8001/api/v1/task/complete
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjUyNTQ2MzgsImV4cCI6MTY2NTI1ODIzOCwicm9sZXMiOlsiUk9MRV9BRE1JTiJdLCJ1c2VybmFtZSI6ImFkbWluQGxvY2FsaG9zdC5kZXYiLCJ1c2VySWQiOiIwMTgzYjhkMC0xOTJkLTdhYTQtODA0Ni1lZGNmOGQ0MGU4OGMifQ.jxu-pQ3vVpfJVf2GaRqFyuApyxe1LDQTyI4QDLAfw3O6xz0kZ6DWNt9TGEx7XvPmyh9qelu7dChkbIU17-bLO9TISe6f4VMHqXVdaXftym4HNtT_UkpbzEK18BeCwUwoDQbiq7M3oCSSocLx_T3I0flCJAJE_JB8HiWuQIm-UZYqF3p6BKdzLuCu7bmCvEc6Wl1vhxQFVyS5wStQmZ16s9Gk0JplR9S6zDOdVN4-SpENQz1cRJXClnSyW94DTpl1eJt69jYtl9fwnUK8I4blvOM-Af6aaqvba5pZSqL-y6pPdQ2ga2zIc3DUIaOjDR0VlmwMY-BCjazg2uq7j6SEaA

{
  "taskId": "0183b8fa-7b22-7cd7-8ba9-35cd6572ae6a",
  "userId": "0183b8ef-ac56-7e57-977f-b04dc86cb241"
}

###

GET http://rest.ates-task:8001/api/v1/task/dashboard?page=1&limit=10
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjUyNTQ2MzgsImV4cCI6MTY2NTI1ODIzOCwicm9sZXMiOlsiUk9MRV9BRE1JTiJdLCJ1c2VybmFtZSI6ImFkbWluQGxvY2FsaG9zdC5kZXYiLCJ1c2VySWQiOiIwMTgzYjhkMC0xOTJkLTdhYTQtODA0Ni1lZGNmOGQ0MGU4OGMifQ.jxu-pQ3vVpfJVf2GaRqFyuApyxe1LDQTyI4QDLAfw3O6xz0kZ6DWNt9TGEx7XvPmyh9qelu7dChkbIU17-bLO9TISe6f4VMHqXVdaXftym4HNtT_UkpbzEK18BeCwUwoDQbiq7M3oCSSocLx_T3I0flCJAJE_JB8HiWuQIm-UZYqF3p6BKdzLuCu7bmCvEc6Wl1vhxQFVyS5wStQmZ16s9Gk0JplR9S6zDOdVN4-SpENQz1cRJXClnSyW94DTpl1eJt69jYtl9fwnUK8I4blvOM-Af6aaqvba5pZSqL-y6pPdQ2ga2zIc3DUIaOjDR0VlmwMY-BCjazg2uq7j6SEaA
#Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjUyNTU5NTQsImV4cCI6MTY2NTI1OTU1NCwicm9sZXMiOlsiUk9MRV9ERVZFTE9QRVIiXSwidXNlcm5hbWUiOiJkZXZlbG9wZXIxQGxvY2FsaG9zdC5kZXYiLCJ1c2VySWQiOiIwMTgzYjhlZS1mYjdkLTcyNjItOWFkYi00MThmZjNiNTFmZGEifQ.Revm5AZanRkfCp-On9RMYVQV_Xm6G_DDbZyUCrwOI48ZAN0mETaz3YSWa0YaiXA4k7aRP1i0fhsJNz5NJefXitmzgK-mSe7zpPoqYqN44p6B0q3cQUHCijXH7LV_9gg73hPvnWBSYzkoK7GeKnZNHoPzoGcJA9RbBgZY4zwiq-YMZZxmzXxYrJwiz9Y9Se7yKk8Vitm690kO_ukuEKsyer9Ijm0vFbOW8fy3v6bK7LtqMMZ8LJ-HBMGqCF2FWnudJhGCYGUjpM7yJGYhokqgVVJJUfvBJzCBugrpWadydhnyc5Ie-kBvD8MTY7GjuLY59FnKafJFcoDGb2R9mJPn2A
#Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjUyNTU5OTEsImV4cCI6MTY2NTI1OTU5MSwicm9sZXMiOlsiUk9MRV9ERVZFTE9QRVIiXSwidXNlcm5hbWUiOiJkZXZlbG9wZXI2QGxvY2FsaG9zdC5kZXYiLCJ1c2VySWQiOiIwMTgzYjhlZi00NTJhLTc3MGEtODg5Zi00ZjdkNDU4NjlhNDEifQ.mcFxeCslW7MORvK6lU315xSVz_10OxgrCALn5QDylzhV0MyxyvxewhoJggWUrJzUCJdWIdiLi6L7CG2wGSAtSRmtrSrKiF3uOChoibddthqzoCuAwgHLMYFIYEg6v4gCcd0cPqt946QPHGgKBZJTYDKRs1v_20ZrxYR28_1Wj5zwihG4254JA4kYPb99meSsy_Qcb3682MXmniwFNwu9SFwKH_0KFr34sUbvrNiXF5XRrI3vw6HIIZ7c_bWHdMg9XIAtksQNcbpMQfuHy9Z9rPBlrcOJQuH0IkXVhEmGT3DJlcVgDgwxcigmgalx2uVvxWqiKFKh7QNxiTxsIm4nLg

###

POST http://rest.ates-auth:8003/api/login
Accept: application/json
Content-Type: application/json

{
  "username": "developer6@localhost.dev",
  "password": "developer6"
}
