### Дашборд биллинга общий+персональный в зависимости от роли авторизованного пользователя

GET http://rest.ates-billing:8002/api/v1/dashboard
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjUyNTk1MzUsImV4cCI6MTY2NTI2MzEzNSwicm9sZXMiOlsiUk9MRV9BRE1JTiJdLCJ1c2VybmFtZSI6ImFkbWluQGxvY2FsaG9zdC5kZXYiLCJ1c2VySWQiOiIwMTgzYjhkMC0xOTJkLTdhYTQtODA0Ni1lZGNmOGQ0MGU4OGMifQ.jJVXpb--SbOpfr0RFu3hjtPHE6wM-fR50cJZ6ZEave46lOVdRc8M3pe5j3Iv_1QDj7ojjDUr0A7kpm1VYlL9rWRIp1Ii2O5maZB0b9naMMCa6L_cv02nNanJnwOG0SDc5gL02WP4qdg8gYBHihN0vMWffwCDHcQHjj4fcT6XdnGdQEDE3Y7pqRCuxQKP7wd4asPZ53w3xDIxJWGJzKG75I4nSkaCMdfR_mc3dtjFoORMRyqcdZA15EX8j9QJ5pNCvN2ZviUhqIilOzkiIPidV1pA9834P5UiPkEjPxHQYjL-xTiXHpzhFHDQVY_kETZErwGMl7GsMfebN1x_8BvI_w

### Дашборд аналитики

GET http://rest.ates-billing:8002/api/v1/analitic
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjUyNTk1MzUsImV4cCI6MTY2NTI2MzEzNSwicm9sZXMiOlsiUk9MRV9BRE1JTiJdLCJ1c2VybmFtZSI6ImFkbWluQGxvY2FsaG9zdC5kZXYiLCJ1c2VySWQiOiIwMTgzYjhkMC0xOTJkLTdhYTQtODA0Ni1lZGNmOGQ0MGU4OGMifQ.jJVXpb--SbOpfr0RFu3hjtPHE6wM-fR50cJZ6ZEave46lOVdRc8M3pe5j3Iv_1QDj7ojjDUr0A7kpm1VYlL9rWRIp1Ii2O5maZB0b9naMMCa6L_cv02nNanJnwOG0SDc5gL02WP4qdg8gYBHihN0vMWffwCDHcQHjj4fcT6XdnGdQEDE3Y7pqRCuxQKP7wd4asPZ53w3xDIxJWGJzKG75I4nSkaCMdfR_mc3dtjFoORMRyqcdZA15EX8j9QJ5pNCvN2ZviUhqIilOzkiIPidV1pA9834P5UiPkEjPxHQYjL-xTiXHpzhFHDQVY_kETZErwGMl7GsMfebN1x_8BvI_w

### Эмуляция завершения дня

PUT http://rest.ates-billing:8002/dev/day-ended
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjUyNTk1MzUsImV4cCI6MTY2NTI2MzEzNSwicm9sZXMiOlsiUk9MRV9BRE1JTiJdLCJ1c2VybmFtZSI6ImFkbWluQGxvY2FsaG9zdC5kZXYiLCJ1c2VySWQiOiIwMTgzYjhkMC0xOTJkLTdhYTQtODA0Ni1lZGNmOGQ0MGU4OGMifQ.jJVXpb--SbOpfr0RFu3hjtPHE6wM-fR50cJZ6ZEave46lOVdRc8M3pe5j3Iv_1QDj7ojjDUr0A7kpm1VYlL9rWRIp1Ii2O5maZB0b9naMMCa6L_cv02nNanJnwOG0SDc5gL02WP4qdg8gYBHihN0vMWffwCDHcQHjj4fcT6XdnGdQEDE3Y7pqRCuxQKP7wd4asPZ53w3xDIxJWGJzKG75I4nSkaCMdfR_mc3dtjFoORMRyqcdZA15EX8j9QJ5pNCvN2ZviUhqIilOzkiIPidV1pA9834P5UiPkEjPxHQYjL-xTiXHpzhFHDQVY_kETZErwGMl7GsMfebN1x_8BvI_w

### Авторизация

POST http://rest.ates-auth:8003/api/login
Accept: application/json
Content-Type: application/json

{
  "username": "admin@localhost.dev",
  "password": "admin"
}
