POST http://rest.ates-auth:8003/v1/user
Accept: application/json
Content-Type: application/json

{
  "email": "developer5@developer.com",
  "password": "developer5",
  "role": "ROLE_DEVELOPER"
}

<> 2022-10-01T234324.404.html
<> 2022-10-01T233533.404.html

###